name: Release
on:
  push:
    branches:
      - master
      - develop
      - alpha
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@leafly-com"
      - name: Set up git for commits
        run: |
          git config user.email "devext@leafly.com"
          git config user.name "LeaflyBuilds"
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.LEAFLY_GITHUB_TOKEN }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.LEAFLY_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.LEAFLY_GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: yarn semantic-release
