name: Release
on:
  push:
    branches:
      - master
      - develop
      - alpha
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set up git for commits
        run: |
          git config user.email "tre@tretuna.com"
          git config user.name "TreTuna"
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
